name: adadmin_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^3.1.0
  
  # Networking
  dio: ^5.9.0

  # Storage
  flutter_secure_storage: ^10.0.0
  shared_preferences: ^2.5.3

  # Fonts
  google_fonts: ^6.3.2

  jwt_decoder: ^2.0.1

  fl_chart: ^0.68.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # ğŸ‘‡ AÃ‘ADIMOS EL LOGO AQUÃ
  assets:
    - assets/logoo.png
